### ISSUE TITLE
CI fail: osx-py36

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#177]
Fails due to TLS missing in python. See [log](https://app.circleci.com/pipelines/github/dwavesystems/minorminer/141/workflows/d272f35a-db12-4712-bde3-0346a76939ef/jobs/5356).

**Comment by randomir** [comment]
The reason:
```
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/distiller/.pyenv/versions/3.6.5/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/Users/distiller/.pyenv/versions/3.6.5/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/distiller/.pyenv/versions/3.6.5/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so
  Reason: image not found
```

CircleCI's stock osx image upgraded and left the cached python 3.6.5 binary hanging looking for an ancient libssl.

Two ways forward (I see): a) clear pyenv cache, forcing all python rebuild; or b) upgrade pythons to latest patch version.

I'll go with (b), but to keep cache lean, will reset it, so do (a) as well.
